# .scrutinizer.yml #
tools:
    external_code_coverage:
        timeout: 1200
        runs: 17

checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'
        - 'build/*'
    paths: {  }
