language: php

services:
  - redis
  - memcached
  - mongodb
  - mysql
  - postgresql
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  #- nightly
  #- hhvm
env:
  - DB=apc
  - DB=redis
  - DB=mongodb
  - DB=sqlite
  - DB=mysql
  - DB=pgsql
  - DB=memcached
jobs:
  fast_finish: true
  include:
#    - php: 5.3
#      dist: precise
#      env: DB=memcached # memcached client is broken on PHP 5.3
    - php: 5.3
      dist: precise
      env: DB=apc
    - php: 5.3
      dist: precise
      env: DB=redis
    - php: 5.3
      dist: precise
      env: DB=mongodb
    - php: 5.3
      dist: precise
      env: DB=sqlite
    - php: 5.3
      dist: precise
      env: DB=mysql
    - php: 5.3
      dist: precise
      env: DB=pgsql
#    - php: 5.4
#      dist: trusty
#      env: DB=memcached # memcached client is broken on PHP 5.4
    - php: 5.4
      dist: trusty
      env: DB=apc
    - php: 5.4
      dist: trusty
      env: DB=redis
    - php: 5.4
      dist: trusty
      env: DB=mongodb
    - php: 5.4
      dist: trusty
      env: DB=sqlite
    - php: 5.4
      dist: trusty
      env: DB=mysql
    - php: 5.4
      dist: trusty
      env: DB=pgsql
#    - php: 5.5
#      dist: trusty
#      env: DB=memcached # memcached client is broken on PHP 5.5
    - php: 5.5
      dist: trusty
      env: DB=apc
    - php: 5.5
      dist: trusty
      env: DB=redis
    - php: 5.5
      dist: trusty
      env: DB=mongodb
    - php: 5.5
      dist: trusty
      env: DB=sqlite
    - php: 5.5
      dist: trusty
      env: DB=mysql
    - php: 5.5
      dist: trusty
      env: DB=pgsql
    - php: 7.0
      env: DB=mariadb
      addons:
        mariadb: 5.5
    - php: 7.0
      env: DB=mariadb
      addons:
        mariadb: 10.1
    - php: 7.1
      env: DB=mariadb
      addons:
        mariadb: 5.5
    - php: 7.1
      env: DB=mariadb
      addons:
        mariadb: 10.2
    - php: 7.2
      env: DB=mariadb
      addons:
        mariadb: 5.5
    - php: 7.2
      env: DB=mariadb
      addons:
        mariadb: 10.3
    - php: 7.3
      env: DB=mariadb
      addons:
        mariadb: 5.5
    - php: 7.3
      env: DB=mariadb
      addons:
        mariadb: 10.4
    - php: 7.4
      env: DB=mariadb
      addons:
        mariadb: 5.5
    - php: 7.4
      env: DB=mariadb
      addons:
        mariadb: 10.5
    - php: 8.0
      env: DB=mariadb
      addons:
        mariadb: 5.5
    - php: 8.0
      env: DB=mariadb
      addons:
        mariadb: 10.6
  allow_failures:
    - php: 5.3
    - php: 5.4
    - php: 5.5

install:
  - travis_retry composer self-update && composer install --no-interaction --prefer-source
  - mkdir -p build/logs
  - tests/bin/travis-init.sh
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar

# before_script:
#  - if [[ $TRAVIS_PHP_VERSION =~ ^7 ]]; then phpenv config-rm xdebug.ini; fi

script:
  - if [[ $TRAVIS_PHP_VERSION =~ ^7 ]]; then
      phpdbg -qrr vendor/phpunit/phpunit/phpunit --verbose --colors --coverage-clover=build/logs/clover.xml --coverage-text;
    else
      vendor/bin/phpunit --verbose --colors --coverage-clover build/logs/clover.xml --coverage-text;
    fi

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml;
  - php vendor/bin/coveralls -v

notifications:
  irc: "irc.freenode.org#ouarz"
  email:
    recipients:
      - dev-team@ouarz.net
    on_success: change
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache
